export const USER_AUTH = 'USER_AUTH'
export const USER_REGISTER = 'USER_REGISTER'
export const STORE_AUTH_FIELD = 'STORE_AUTH_FIELD'
export const CONFIRM_AUTH_FIELD = 'CONFIRM_AUTH_FIELD'

export const GET_FUL_DISH_LIST = 'GET_FUL_DISH_LIST'
export const GET_SAMPLE_DISHES = 'GET_SAMPLE_DISHES'
export const GET_DISH = 'GET_DISH'
export const TOGGLE_FUL_LIST = 'TOGGLE_FUL_LIST'

export const GET_LAYOUT_TYPE = 'GET_LAYOUT_TYPE'
export const IS_VALID_FIELD_UI = 'IS_VALID_FIELD_UI'